### ISSUE TITLE
Getting a count of the number of descendants category within multiple categories?

### ISSUE THREAD

**Issue by viztastic** [Voronenko/Storing_TreeView_Structures_WithMongoDB#1]
Hi @Voronenko 

Thanks for this, this is really helpful.

A quesiton, I am using the materialized path strategy and I want to:
- [x] Retrieve all top level items (i.e. find({path:null}))
- [ ] Include a count of the number of descendants within each category 

Is this best done using aggregation framework?

**Comment by Voronenko** [comment]
I would use series of the queries, and cache them afterwards.

i.e. iterate over top nodes (find({path:""})))
then for each found top level node execute smth like
var item = db.categoriesMP.findOne({_id:"Cell_Phones_and_Accessories"});

var criteria = '^'+item.path+item._id+',';
var descendantscount = db.categoriesMP.find({path: { $regex: criteria, $options: 'i' }}).count();

Or, if your case requires collecting these figures,  perhaps introduce count field at top nodes, and increment it on your own with $inc

**Comment by Voronenko** [comment]
due to inactivity.
